name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Start xcodebuild test
      run: xcodebuild clean build -project BLEUnlock.xcodeproj -scheme BLEUnlock -configuration Debug CODE_SIGN_IDENTITY=- DEVELOPMENT_TEAM=
